spring.application.name=jobpoltal
logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:file:D:\\sql\\jobportal;AUTO_SERVER=true
spring.datasource.username=rahul
spring.datasource.password=rahul
spring.datasource.driver-class-name=org.h2.Driver

#the servlet context path is used because it wants you to use /backend prefix before accessing any api's, like if
#you want to add a prefix in fron of an API
#server.servlet.context-path=/backend

#spring.sql.init.mode=embedded this property will create the H2 data base by default its embedded
spring.sql.init.schema-locations=classpath:sql/Jobportal-Schema.sql
#If the data.sql file is not found the application fails during startup itself to avoid that you can
#use optional
#spring.sql.init.data-locations=optional:classpath:sql/Jobportal-data.sql.
spring.sql.init.data-locations=classpath:sql/Jobportal-data.sql

#spring.sql.init.mode=always




