spring.application.name=jobpoltal
logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}

#the servlet context path is used because it wants you to use /backend prefix before accessing any api's, like if
#you want to add a prefix in fron of an API
#server.servlet.context-path=/backend


